version: "3"
networks:
  app_network:
  db:
    external: true

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - "8000:80"
    links:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - php
    networks:
      - app_network
      - db

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - app_network
      - db
